#!/usr/bin/env bash

### Variables ###

count=1

reset="\033[0m"
highlight="\033[41m\033[97m"
dot="\033[31m▸ $reset"
dim="\033[2m"
black=$(tput setaf 0)
purple="\033[1;35m"
red=$(tput setaf 1)
green=$(tput setaf 2)
yellow=$(tput setaf 3)
blue=$(tput setaf 4)
magenta=$(tput setaf 5)
cyan=$(tput setaf 6)
white=$(tput setaf 7)
tag_green="\e[30;42m"
tag_blue="\e[30;46m"
bold=$(tput bold)
normal=$(tput sgr0)
underline="\e[37;4m"
indent="   "

sierra=10.12.2
catalina=10.15

internet=false

env=null

# Get full directory name of this script
cwd="$(cd "$(dirname "$0")" && pwd)"

# Home location
# location='${HOME}/greenhouse/'
location='${PWD}'

### Text Formatting ###

# Display outputted text in a chosen colour.
cecho() {
    echo "${2}${1}${reset}"
    return
}

# Create a formatted heading in the terminal.
heading() {
    local head="$1"; shift
    cecho "\n  ${bold}$((count++)). $head${normal}\n ─────────────────────────────────────────────────────\n" $white
}

installing() {
    local install="$1"; shift
    printf "  [↓] $install " "$@"
}

step() {
    printf "\n   ${dot}${underline}$@${reset}\n"
}

### System checks ###

# Get the current bash version running.
check_bash_version() {
    if ((BASH_VERSINFO[0] < 3)); then
        print_error "Sorry, you need at least bash-3.0 to run this script."
        exit 1
    fi
}

# Get and display the system's OS.
get_os() {

    local os=""
    local kernelName=""

    kernelName="$(uname -s)"

    if [ "$kernelName" == "Darwin" ]; then
        os="macOS"
    elif [ "$kernelName" == "Linux" ] && [ -e "/etc/lsb-release" ]; then
        os="ubuntu"
    else
        os="$kernelName"
    fi

    printf "%s" "$os"

}

# Get the current version of the system's OS.
get_os_version() {

    local os=""
    local version=""

    os="$(get_os)"

    if [ "$os" == "macOS" ]; then
        version="$(sw_vers -productVersion)"
    elif [ "$os" == "ubuntu" ]; then
        version="$(lsb_release -d | cut -f2 | cut -d' ' -f2)"
    fi

    echo $version

}

# Check if the current session has access to the internet.
check_internet_connection() {
    if [ ping -q -w1 -c1 google.com ] &>/dev/null; then
        cecho "No internet found! Please check your internet connection." $red
        exit 0
    else
        cecho "You have an internet connection!" $green
        internet=true
    fi
}

# Cache the sudo password.
admin_pass() {
    # Ask for the administrator password upfront.

    sudo -v &>/dev/null

    # Update existing `sudo` time stamp
    # until this script has finished.
    #
    # https://gist.github.com/cowboy/3118588

    # Keep-alive: update existing `sudo` time stamp until script has finished
    while true; do
        sudo -n true
        sleep 60
        kill -0 "$$" || exit
    done 2>/dev/null &

    cecho "Password cached to system." $green

}

### Misc ###
create_ssh_config() {
touch ~/.ssh/config
cat <<EOT >> ~/.ssh/config
	Host *
		AddKeysToAgent yes
		UseKeychain yes
        ForwardAgent yes
        IdentitiesOnly yes
        IdentityFile ~/.ssh/id_rsa
EOT
}

setup_nvm() {
local shellEnv=''

if [ $(grep "zsh" $location/storage/shell.log) ]; then
    shellEnv='~/.zsh_modules/.exports'
else
    shellEnv='~/.bash_modules/.exports'
fi

if [ ! $(grep "nvm" $location/seeds/brews) ];
then
cat <<EOT >> $shellEnv
# NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
export PATH="$HOME/.npm-packages/bin:$PATH"
EOT
else
cat <<EOT >> $shellEnv
# NVM
export NVM_DIR=~/.nvm
export PATH="$HOME/.npm-packages/bin:$PATH"
source $(brew --prefix nvm)/nvm.sh
EOT
fi

}

install_with_yarn() {

local shellEnv=''

if [ $(grep "zsh" $location/storage/shell.log) ]; then
    shellEnv='~/.zsh_modules/.exports'
else
    shellEnv='~/.bash_modules/.exports'
fi

cat <<EOT >> $shellEnv
export PATH="$(yarn global bin):$PATH"
EOT

}

supress_zsh_warning() {

cat <<EOT >> ~/.bash_profile/.exports
# Supress zsh warning
export BASH_SILENCE_DEPRECATION_WARNING=1
EOT

}