#!/usr/bin/env bash

### ERROR: display error if script failure. ###
trap 'ret=$?; test $ret -ne 0 && printf "\n   ⛔️\e\033[0;31m  Germination failed!! \e\033[0m ⛔️\n" >&2; exit $ret' EXIT

set -e

### Get required file ###
if [ -e fertilise ]; then
	cd "$(dirname "${BASH_SOURCE[0]}")" \
		&& . "fertilise"
else
	printf "\n ⚠️ ./fertilise not found.\n"
	exit 1
fi

### Run Inital Script ###

printf "
  ___  ____  ____  __  __  ____  _  _    __   ____  ____ 
 / __)( ___)(  _ \(  \/  )(_  _)( \( )  /__\ (_  _)( ___)
( (_-. )__)  )   / )    (  _)(_  )  (  /(__)\  )(   )__) 
 \___/(____)(_)\_)(_/\/\_)(____)(_)\_)(__)(__)(__) (____)

LET'S START ${bold}PLANTING${normal}!
This is a shell script that aims to setup and/or maintain your Mac.
The script will ${green}install${reset}, ${blue}update${reset}, ${purple}backup${reset}, ${red}restore${reset}, or ${yellow}skip${reset} packages.

----
${bold}System Info:${normal}
// OS: ${dim}$(get_os) ${normal} // OS Version: ${dim}$(get_os_version) ${normal} // Shell: ${dim}$BASH ${normal} // Shell Version: ${dim}$BASH_VERSION${reset}

${dim}Copyright © 2020 | Mathew Teague.${normal}
----

\n
"


## Pre-install checks
heading "Checking your internet connection…"
check_internet_connection

# heading "Admin password"
# admin_pass
if [ ! -f "$HOME/greenhouse/shell.log" ]; then
	echo "Which shell would you like to us? b/z"
	read shell
	touch greenhouse/shell.log
	if [ "$(printf '%s\n' "$catalina" "$version" | sort -V | head -n1)" = "$catalina" ]; then
		if [[ $shell =~ ^([bB][bashBash]|[bB])$ ]]; then
			chsh -s /bin/bash
			echo "bash" > ${HOME}/greenhouse/shell.log
		else
			chsh -s /bin/zsh
			echo "zsh" > ${HOME}/greenhouse/shell.log
		fi
	else
		if [[ $shell =~ ^([zZ][zshZSH]|[zZ])$ ]]; then
			echo "install zsh"
			echo "zsh" >> ${HOME}/greenhouse/shell.log
		fi
	fi
else
	printf "It looks like you have a shell environment set. Would you like to change it? y/N"
	read shellChange
	if [[ $shellChange =~ ^([yY])$ ]]; then
		if [ "$(printf '%s\n' "$catalina" "$version" | sort -V | head -n1)" = "$catalina" ]; then
			if [[ if shell.log has zsh ]]; then
				chsh -s /bin/bash
				echo "bash" > ${HOME}/greenhouse/shell.log
			else
				chsh -s /bin/zsh
				echo "zsh" > ${HOME}/greenhouse/shell.log
			fi
		else
			if [[ if shell.log has bash ]]; then
				echo "install zsh"
				echo "zsh" >> ${HOME}/greenhouse/shell.log
			else
				echo "uninstall zsh"
				echo "bash" >> ${HOME}/greenhouse/shell.log
			fi
		fi
	else
		cecho "Shell already configured. Skipping." $dim
	fi
fi

#open https://download.filezilla-project.org/client/FileZilla_3.46.3_macosx-x86_sponsored-setup.dmg

#open https://get.popcorntime.sh/build/Popcorn-Time-0.3.10-Mac.zip