## Taps
tap "1password/tap"
tap "github/gh"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "mongodb/brew"
tap "universal-ctags/universal-ctags"
tap "mklement0/ttab", "https://github.com/mklement0/ttab.git"
tap "sass/sass"
tap "shopify/shopify"

## Cask dependencies
brew "mas"

## Shells
## Note: Don't forget to add shells to `/etc/shells` before running `chsh`.
brew "bash"
brew "zsh"

## Brews
## Don't forget to add `$(brew --prefix coreutils)/libexec/gnubin` to `$PATH`.
brew "brotli"
brew "coreutils"
brew "curl"
brew "ffmpeg"
brew "gd"
brew "gh"
brew "git"
brew "glib"
brew "git-extras"
brew "git-secrets"
brew "graphicsmagick"
brew "grep"
brew "gzip"
brew "highlight"
brew "hub"
brew "imagemagick"
brew "jpeg"
brew "lua"
brew "mkcert"
brew "mongodb-community" # MongoDB
brew "moreutils" # Install more useful GNU utilities like `sponge`
brew "multimarkdown" # Markdown
brew "mysql", restart_service: true # MySQL DB
brew "nginx", restart_service: true
brew "nss"
brew "nvm" # Node version manager
brew "openldap"
brew "openssh"
brew "openssl"
brew "openssl@1.1"
brew "rbenv" # Ruby
brew "rsync"
brew "ruby"
brew "ruby-build"
brew "php", restart_service: true
brew "pnpm"
brew "pyenv" # Python
brew "shellcheck" # Bash and sh script linting
brew "speedtest_cli"
brew "ssh-copy-id"
brew "tree"
brew "webp"
brew "wget"
brew "wifi-password"
brew "yarn"
brew "youtube-dl"
brew "yt-dlp"
brew "zsh-autocomplete"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

## Install applications
cask "1password"
cask "1password-cli"
cask "adobe-acrobat-reader"
cask "aerial"
cask "android-studio"
cask "appcleaner"
cask "arc"
cask "brave-browser"
cask "coconutbattery"
cask "dash"
cask "docker"
cask "figma"
cask "firefox"
cask "github"
cask "google-chrome"
cask "google-drive"
cask "grammarly"
cask "handbrake"
cask "hyper"
cask "imageoptim"
cask "iterm2"
cask "keka"
cask "macupdater"
cask "makemkv"
cask "microsoft-edge"
cask "mkvtoolnix"
cask "mark-text"
cask "nordlocker"
cask "nucleo"
cask "opera"
cask "postman"
cask "screaming-frog-seo-spider"
cask "sequel-pro"
cask "spotify"
cask "synology-drive"
cask "topaz-gigapixel-ai"
cask "typeface"
cask "visual-studio-code"
cask "vlc"
cask "webpquicklook"
cask "whatsapp"

## Fonts
cask "font-fira-code"
cask "font-fira-mono-for-powerline"
cask "font-fira-sans"
cask "font-jetbrains-mono"

## VSCode
vscode "be5invis.toml"
vscode "bradlc.vscode-tailwindcss"
vscode "csstools.postcss"
vscode "dbaeumer.vscode-eslint"
vscode "EditorConfig.EditorConfig"
vscode "esbenp.prettier-vscode"
vscode "formulahendry.auto-close-tag"
vscode "formulahendry.auto-rename-tag"
vscode "ginfuru.ginfuru-vscode-jekyll-syntax"
vscode "ginfuru.vscode-jekyll-snippets"
vscode "hollowtree.vue-snippets"
vscode "junstyle.php-cs-fixer"
vscode "killalau.vscode-liquid-snippets"
# vscode "mateuspv.shopify-schema-settings-snippets"
vscode "mikestead.dotenv"
vscode "mrmlnc.vscode-apache"
vscode "octref.vetur"
vscode "PKief.material-icon-theme"
vscode "rebornix.toggle"
vscode "redhat.vscode-yaml"
vscode "sissel.shopify-liquid"
vscode "streetsidesoftware.code-spell-checker"
vscode "syler.sass-indented"
vscode "tamasfe.even-better-toml"
vscode "toba.vsfire"
vscode "Vue.volar"
vscode "whizkydee.material-palenight-theme"

## mas apps
mas "Affinity Designer", id: 824171161
mas "Affinity Photo", id: 824183456
mas "Amphetamine", id: 937984704
mas "Compressor", id: 424390742
mas "Encrypto", id: 935235287
mas "Final Cut Pro", id: 424389933
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "LittleIpsum", id: 405772121
mas "Magnet", id: 441258766
mas "Motion", id: 434290957
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Shazam", id: 897118787
mas "Slack", id: 803453959
mas "SnippetsLab", id: 1006087419
mas "Speedtest", id: 1153157709
mas "Surfshark", id: 1437809329
mas "The Unarchiver", id: 425424353
